# Generated by Django 4.2.4 on 2024-04-03 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_age_user_gender_user_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreadmillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField()),
                ('duration', models.DurationField()),
                ('speed', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('calories_burned', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
